AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: FastAPI on Lambda + API Gateway HTTP API v2

Parameters:
  Environment:
    Type: String
    Default: development
    AllowedValues: [development, production]
    Description: Environment name
  ApiGatewayStageName:
    Type: String
    Default: $default
    Description: HTTP API stage name ($default recommended)
  VpcId:
    Type: String
    Default: ""
    Description: (Optional) VPC ID. Leave empty if not using VPC.
  SubnetIds:
    Type: CommaDelimitedList
    Default: ""
    Description: (Optional) Subnet IDs (comma-separated). Leave empty if not using VPC.
  SecurityGroupIds:
    Type: CommaDelimitedList
    Default: ""
    Description: (Optional) Security Group IDs (comma-separated). Leave empty if not using VPC.

Conditions:
  HasVPC: !And
    - !Not [ !Equals [ !Ref VpcId, "" ] ]
    - !Not [ !Equals [ !Select [0, !Ref SubnetIds], "" ] ]
    - !Not [ !Equals [ !Select [0, !Ref SecurityGroupIds], "" ] ]
  IsProd: !Equals [!Ref Environment, "production"]

Globals:
  Function:
    Timeout: 30
    MemorySize: 512
    Runtime: python3.11
    Architectures: [x86_64]
    Tracing: Active
    Environment:
      Variables:
        ENVIRONMENT: !Ref Environment
        LOG_LEVEL: !If [IsProd, "info", "debug"]
        PYTHONPATH: /var/task
    LoggingConfig:
      LogFormat: JSON
      ApplicationLogLevel: INFO
      SystemLogLevel: INFO
      LogGroup: !Sub "/aws/lambda/${AWS::StackName}"
    VpcConfig: !If
      - HasVPC
      - 
        SecurityGroupIds: !Ref SecurityGroupIds
        SubnetIds: !Ref SubnetIds
      - !Ref "AWS::NoValue"

Resources:
  FastAPIHttpApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      StageName: !Ref ApiGatewayStageName
      CorsConfiguration:
        AllowCredentials: false
        AllowHeaders: ["*"]
        AllowMethods: [GET, POST, PUT, PATCH, DELETE, OPTIONS]
        AllowOrigins: ["*"]
        MaxAge: 600

  FastAPIFunction:
    Type: AWS::Serverless::Function
    Properties:
      Description: FastAPI Lambda Function
      CodeUri: ./
      Handler: app.lambda_handler.handler
      Events:
        AnyRoute:
          Type: HttpApi
          Properties:
            ApiId: !Ref FastAPIHttpApi
            Method: ANY
            Path: /{proxy+}
        Root:
          Type: HttpApi
          Properties:
            ApiId: !Ref FastAPIHttpApi
            Method: ANY
            Path: /
      Policies:
        - CloudWatchLogsFullAccess
      # (Opcional) Ajustes adicionales:
      # Layers: [arn:aws:lambda:...:layer:your-shared-layer:1]

Outputs:
  ApiUrl:
    Description: "HTTP API URL"
    Value: !Sub "https://${FastAPIHttpApi}.execute-api.${AWS::Region}.amazonaws.com/${ApiGatewayStageName == '$default' ? '' : ApiGatewayStageName}"
  FunctionName:
    Description: "Lambda Function Name"
    Value: !Ref FastAPIFunction
